spring.application.name=SteirerTech_WebShop_RestController
# ===============================
# = DATA SOURCE
# ===============================
# Set here configurations for the database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/steirertechdb
spring.datasource.username=postgres
spring.datasource.password=geheim123
spring.datasource.driver-class-name=org.postgresql.Driver
# ===============================
# = JPA / HIBERNATE
# ===============================
# Show or not log for each sql query
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
